- name: tooltip
  regex: S:(.+tooltip|gt.tooltip.+)
- name: oredict
  regex: S:oredict.+
- name: qt
  regex: S:qwertech.+
- name: gt_block
  regex: S:gt.block.+
- name: gt_drink
  regex: S:gt.drink.+
- name: gt_lang
  regex: S:gt.lang.+
- name: gt_material
  regex: S:gt.material.+
- name: gt_meta
  regex: S:gt.meta(tool)?.+
- name: gt_multiitem
  regex: S:gt.multiitem.+
- name: gt_multitileentity
  regex: S:gt.multitileentity.+
- name: gt_recipe
  regex: S:gt.recipe.+
- name: gt_stone
  regex: S:gt.stone.+
- name: gt_td
  regex: S:gt.td.+
- name: gt_misc
  regex: S:gt\..+
- name: fluid
  regex: S:fluid.+
- name: compact
  regex: S:(bc|tc|ic2?).+
- name: itemGroup
  regex: S:itemGroup.+
- name: misc
  regex: S:.+
