S:gt.material.AnyCoalCarbon: 任意煤炭或碳
S:gt.material.AnyIronOrSteel: 任意钢或铁
S:gt.material.AnyStone: 任意种类的石头
S:gt.material.AnyWood: 任意木头
S:oredict.blockDustBone.name: 骨粉块
S:oredict.gemEmpty.name: 空宝石
S:oredict.ingotSteeleaf.name: 钢叶锭
S:oredict.oreBasalticMineralSand.name: 玄武岩砂
S:oredict.oreQuartziteQuartzBlack.name: 黑色石英岩矿石
S:oredict.oreQuartziteQuartzSand.name: 石英沙矿石
S:oredict.oreQuartziteQuartzite.name: 石英岩矿石